name: GameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare WordPress Zip
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $WP_LINK

      - name: Prepare plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes

      - name: Copy Zips to Server
        uses: appleboy/scp-action@master
        with:
          host: ftp.proshohan.com
          username: u714669472.shohan007
          password: Shohan_007
          port: 21
          source: "./wordpress.zip, ./wpcontent.zip"
          target: ${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}

      - name: Enable Maintenance Mode
        uses: appleboy/scp-action@master
        with:
          host: ftp.proshohan.com
          username: u714669472.shohan007
          password: Shohan_007
          port: 21
          source: ".maintenance"
          target: ${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}

      - name: Update WordPress Core
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ftp.proshohan.com
          username: u714669472.shohan007
          password: Shohan_007
          port: 21
          script: |
            find "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}" -type f -name "*.php" ! -name "wp-config.php" -delete
            rm -r "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wp-admin/" "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wp-includes/"
            unzip -o "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wordpress.zip" -d "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/"
            mv "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wordpress"/* "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/"
            rm -r "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wordpress"

      - name: Update Plugins and Theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ftp.proshohan.com
          username: u714669472.shohan007
          password: Shohan_007
          port: 21
          script: |
            rm -rf "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wp-content/plugins" "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wp-content/mu-plugins" "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wp-content/themes"
            unzip -o "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wpcontent.zip" -d "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wp-content/"

      - name: Disable Maintenance Mode and Remove zips
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ftp.proshohan.com
          username: u714669472.shohan007
          password: Shohan_007
          port: 21
          script: |
            rm -f "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/.maintenance"
            rm -f "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wpcontent.zip"
            rm -f "${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}/wordpress.zip" 
