name: GameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_PATH: ${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare WordPress Zip
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $WP_LINK

      - name: Prepare plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes

      - name: Copy Zips to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./wordpress.zip, ./wpcontent.zip"
          target: "${{ env.DEPLOY_PATH }}"

      - name: Enable Maintenance Mode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: ".maintenance"
          target: "${{ env.DEPLOY_PATH }}"

      - name: Update WordPress Core
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            find "${DEPLOY_PATH}" -type f -name "*.php" ! -name "wp-config.php" -delete
            rm -r "${DEPLOY_PATH}/wp-admin/" "${DEPLOY_PATH}/wp-includes/"
            unzip -o "${DEPLOY_PATH}/wordpress.zip" -d "${DEPLOY_PATH}/"
            mv "${DEPLOY_PATH}/wordpress"/* "${DEPLOY_PATH}/"
            rm -r "${DEPLOY_PATH}/wordpress"

      - name: Update Plugins and Theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf "${DEPLOY_PATH}/wp-content/plugins" "${DEPLOY_PATH}/wp-content/mu-plugins" "${DEPLOY_PATH}/wp-content/themes"
            unzip -o "${DEPLOY_PATH}/wpcontent.zip" -d "${DEPLOY_PATH}/wp-content/"

      - name: Disable Maintenance Mode and Remove zips
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -f "${DEPLOY_PATH}/.maintenance"
            rm -f "${DEPLOY_PATH}/wpcontent.zip"
            rm -f "${DEPLOY_PATH}/wordpress.zip"
