name: GameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prepare WordPress Zip
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $WP_LINK

      - name: Prepare plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes

      - name: Copy Zips to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./wordpress.zip ./wpcontent.zip"
          target: ${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}

      - name: Enable Maintenance Mode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: ".maintenance"
          target: ${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}

      - name: Update WordPress Core
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            DIR=${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}
            find "$DIR" -type f -name "*.php" ! -name "wp-config.php" -delete
            rm -r "$DIR/wp-admin/" "$DIR/wp-includes/"
            unzip -o "$DIR/wordpress.zip" -d "$DIR/"
            mv "$DIR/wordpress/"* "$DIR/"
            rm -r "$DIR/wordpress"

      - name: Update Plugins and Theme
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            DIR=${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}
            rm -rf "$DIR/wp-content/plugins" "$DIR/wp-content/mu-plugins" "$DIR/wp-content/themes"
            unzip -o "$DIR/wpcontent.zip" -d "$DIR/wp-content/"

      - name: Disable Maintenance Mode and Remove zips
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            DIR=${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}
            rm -f "$DIR/.maintenance"
            rm -f "$DIR/wpcontent.zip"
            rm -f "$DIR/wordpress.zip"

      - name: Debug: Confirm Files on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            DIR=${{ github.event_name == 'push' && 'public_html/gamestoredev' || 'public_html/gamestore' }}
            echo "Files in $DIR:"
            ls -lh "$DIR"
